apiVersion: v1
kind: Pod
metadata:
  name: nginx-stress
spec:
  containers:
  - name: nginx
    image: ubuntu/nginx
    ports:
    - containerPort: 80
  - name: stress
    image: progrium/stress
    command: ["stress", "--cpu", "2", "--io", "1", "--vm", "1", "--vm-bytes", "128M", "--timeout", "60s"]
